PREFIX nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbpedia: <http://dbpedia.org/resource/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/access-for-role/PubliekeBesluitendatabank-BesluitendatabankLezer> {
    <share://semantic-forms/20221013091443-forms.ttl> a nfo:FileDataObject ;
      dct:type <http://data.lblod.gift/concepts/form-file-type> ;
      mu:uuid "2706e812-4828-4b0d-8ffd-77c884eff90e" ;
      nfo:fileName "20221013091443-forms.ttl" ;
      dct:created "2022-10-13T09:14:43"^^xsd:dateTime ;
      dct:modified "2022-10-13T09:14:43"^^xsd:dateTime ;
      dct:format "text/turtle";
      nfo:fileSize "328922"^^xsd:integer;
      dbpedia:fileExtension "ttl" .
  }
}
    