version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
  virtuoso:
    ports:
      - "8890:8890"
  mocklogin:
    image: lblod/mock-login-service:0.4.0
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/access-for-role/PubliekeBesluitendatabank-BesluitendatabankLezer"
    links:
      - virtuoso:database
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    user: root
    command: /usr/local/bin/kibana-docker --allow-root
    restart: "no"
