x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    image: lblod/frontend-public-decisions:1.10.0
    volumes:
      - ./config/frontend:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.11.0
    links:
      - dispatcher:dispatcher
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.3.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini # Note: on production override this setting
      - ./config/virtuoso/:/opt/virtuoso-scripts
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.27.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  login:
    image: lblod/acmidm-login-service:0.12.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "b772fce4-ebd8-4980-b51c-8e0d73fe75d2"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://besluiten.lokaalbestuur.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
      MU_APPLICATION_AUTH_USERID_CLAIM: "sub"
      MU_APPLICATION_AUTH_ACCOUNTID_CLAIM: "sub"
      MU_APPLICATION_AUTH_ROLE_CLAIM: "abb_besluitendatabank_rol_2d"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_TIMEOUT: '300'
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.4.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  search:
    image: semtech/mu-search:feature-maintenance-cli
    volumes:
      - ./config/search:/config
      - ./data/files:/data
      - ./data/tika/cache:/cache
    environment:
      NUMBER_OF_THREADS: 16 # overwrite for development
      JRUBY_OPTIONS: "-J-Xmx16g" # overwrite for development
    restart: always
    logging: *default-logging
  elasticsearch:
    image: semtech/mu-search-elastic-backend:1.1.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - http.max_content_length=2000MB
    restart: always
    logging: *default-logging
  tika:
    image: apache/tika:1.24-full
    logging: *default-logging
    restart: always
    labels:
      - "logging=true"
  search-query-management:
    image: lblod/toezicht-search-query-management-service:0.3.7
    volumes:
      - ./config/search-query:/share/search-query
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  enrich-submission:
    image: lblod/enrich-submission-service:1.13.5
    volumes:
      - ./config/semantic-forms:/share/semantic-forms
      - ./data/files/submissions:/share/submissions
    environment:
      ACTIVE_FORM_FILE: "share://semantic-forms/20250610135731-forms.ttl"
      PUBLIC_GRAPH: "http://mu.semte.ch/graphs/access-for-role/PubliekeBesluitendatabank-BesluitendatabankLezer"
      FILE_GRAPH: "http://mu.semte.ch/graphs/access-for-role/PubliekeBesluitendatabank-BesluitendatabankLezer"
      OVERRULE_ORG_CHECK_ON_READ: "true"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
################################################################################
# DELTAS
################################################################################
  submissions-consumer:
      image: lblod/delta-consumer:0.1.6
      environment:
        DCR_SYNC_BASE_URL: 'https://loket.lblod.info/'
        DCR_SERVICE_NAME: 'submissions-consumer'
        DCR_SYNC_FILES_PATH: '/sync/submissions/files'
        DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/SubmissionsCacheGraphDump"
        DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/submissions"
        DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/submissions-consumer"
        DCR_DISABLE_INITIAL_SYNC: 'true'
        DCR_KEEP_DELTA_FILES: 'true'
        DCR_DELTA_FILE_FOLDER: '/consumer-files'
        DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/sumbissionFileSyncing"
        INGEST_GRAPH: "http://mu.semte.ch/graphs/access-for-role/PubliekeBesluitendatabank-BesluitendatabankLezer"
        BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: 'true'
        FILE_SYNC_GRAPH: "http://mu.semte.ch/graphs/original-physical-files-data"
      volumes:
        - ./config/delta-consumers/submissions-consumer/submissions-dispatching:/config/triples-dispatching/custom-dispatching
        - ./data/files/consumer-files/submissions:/consumer-files/
        - ./data/files:/share
      labels:
        - "logging=true"
      restart: always
      logging: *default-logging
  files-consumer:
    image: lblod/delta-consumer-file-sync-submissions:0.5.1
    environment:
      DISABLE_AUTOMATIC_SYNC: "true"
      DISABLE_INITIAL_SYNC: "true"
      FILES_ENDPOINT_BASE_URL: "https://loket.lblod.info"
      SOURCE_FILES_DATA_GRAPH: "http://mu.semte.ch/graphs/original-physical-files-data"
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  ################################################################################
  # OP CONSUMERS
  ################################################################################
  op-consumer:
    image: lblod/delta-consumer:0.1.6
    environment:
      DCR_SERVICE_NAME: "op-consumer"
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info" # replace with link to OP API
      DCR_SYNC_FILES_PATH: "/sync/public/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/PublicCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/op-public"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/op-public"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-public-consumer"
      DCR_DISABLE_INITIAL_SYNC: "true"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_JOBS_RETENTION_PERIOD: "30"
      DCR_ENABLE_TRIPLE_REMAPPING: "true"
      DCR_LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/landing-zone/op-public"
      DCR_REMAPPING_GRAPH: "http://mu.semte.ch/graphs/access-for-role/PubliekeBesluitendatabank-BesluitendatabankLezer"
      DCR_BATCH_SIZE: 1000
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: "404,500,503"
      SUDO_QUERY_RETRY: "true"
    volumes:
      - ./config/delta-consumers/op-consumer/mapping:/config/mapping
      - ./data/files/consumer-files/op-public:/consumer-files/
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  # Some data is needed in the public graph for acm/idm to work
  op-consumer-for-auth:
    image: lblod/delta-consumer:0.1.6
    environment:
      DCR_SERVICE_NAME: "op-consumer-for-auth"
      DCR_SYNC_BASE_URL: "https://organisaties.abb.lblod.info" # replace with link to OP API
      DCR_SYNC_FILES_PATH: "/sync/public/files"
      DCR_SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/PublicCacheGraphDump"
      DCR_INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/op-for-auth"
      DCR_DELTA_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/op-for-auth"
      DCR_JOB_CREATOR_URI: "http://data.lblod.info/services/id/op-consumer-for-auth"
      DCR_DISABLE_INITIAL_SYNC: "true"
      DCR_KEEP_DELTA_FILES: "true"
      DCR_DELTA_JOBS_RETENTION_PERIOD: "30"
      DCR_ENABLE_TRIPLE_REMAPPING: "true"
      DCR_LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/landing-zone/op-public"
      DCR_REMAPPING_GRAPH: "http://mu.semte.ch/graphs/public"
      DCR_BATCH_SIZE: 1000
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: "404,500,503"
      SUDO_QUERY_RETRY: "true"
    volumes:
      - ./config/delta-consumers/op-consumer-for-auth/mapping:/config/mapping
      - ./data/files/consumer-files/op-public:/consumer-files/
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
