PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mu:<http://mu.semte.ch/vocabularies/core/>
PREFIX ext:<http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/persoon/8f3ee4e5-20a7-4fe9-a953-fcb6bc81fd76> a foaf:Person ;
      mu:uuid "8f3ee4e5-20a7-4fe9-a953-fcb6bc81fd76" ;
      foaf:firstName "Lezer" ;
      foaf:familyName "VVSG" ;
      foaf:member <http://data.lblod.info/id/bestuurseenheden/0a2af324-e4d2-4b6d-9d81-1b50198762a> ;
      foaf:account <http://data.lblod.info/id/account/97cbabd8-a53a-4b42-bd21-7054f1daaa71> .
    <http://data.lblod.info/id/account/97cbabd8-a53a-4b42-bd21-7054f1daaa71> a foaf:OnlineAccount ;
      mu:uuid "97cbabd8-a53a-4b42-bd21-7054f1daaa71" ;
      foaf:accountServiceHomepage <https://github.com/lblod/mock-login-service>;
      ext:sessionRole "BesluitendatabankGebruiker" .
  }
}
